import type { NextPage } from "next";
import Head from "next/head";
import Button from "../components/Button";
import Title from "../components/Title";
import MainContainer from "../containers/MainContainer";
import MainLayout from "../layouts/MainLayout";
import NftShowcase from "../sections/NftShowcase";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Boilerplate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <NftShowcase />
      </MainLayout>
    </>
  );
};

export default Home;
